export const ProjectActionTypes = {
    CHANGE_SEARCH_FIELD: 'CHANGE_SEARCH_FIELD',
    REQUEST_PROJECTS_LOADING: 'REQUEST_PROJECTS_LOADING',
    REQUEST_PROJECTS_SUCCESS: 'REQUEST_PROJECTS_SUCCESS',
    REQUEST_PROJECTS_FAILED: 'REQUEST_PROJECTS_FAILED',    
    ADD_PROJECT_SUCCESS: 'ADD_PROJECT_SUCCESS',
    ADD_PROJECT_FAILED: 'ADD_PROJECT_FAILED'
}